In [1]:
import torch
import torch.nn as nn

### Câu 1:

In [2]:
data = torch.Tensor([1, 2, 3])
softmax_function = nn.Softmax(dim=0)
output = softmax_function(data)
assert round(output[0].item(), 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

### Câu 2.

In [3]:
class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        softmax = nn.Softmax(dim=0)
        output = softmax(x)
        return output


data = torch.Tensor([5, 2, 4])
my_softmax = MySoftmax()
output = my_softmax(data)
output

tensor([0.7054, 0.0351, 0.2595])

### Câu 3.

In [5]:
data = torch.Tensor([1, 2, 30000000000])
my_softmax = MySoftmax()
output = my_softmax(data)
output

tensor([0., 0., 1.])

### câu 4

In [6]:
class SoftmaxStable(nn.Module):
    def __init__(self) -> None:
        super().__init__()

    def forward(self, x):
        x_max = torch.max(x, dim=0, keepdim=True)
        x_exp = torch.exp(x - x_max.values)
        partition = x_exp.sum(0, keepdim=True)
        return x_exp/partition
    
data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
output

tensor([0.0900, 0.2447, 0.6652])

### Câu 5.

In [7]:
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name:str, yob:int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob
    
    @abstractmethod
    def describe(self):
        pass


class Student(Person):
    def __init__(self, name: str, yob: int, grade:str):
        super().__init__(name, yob)
        self._grade = grade

    
    def describe(self):
        return f'Name: {self._name} - Yob: {self._yob} - grade: {self._grade}'
    

student1 = Student(name='studentZ2023', yob=2011, grade='6')
assert student1._yob == 2011
student1.describe()


'Name: studentZ2023 - Yob: 2011 - grade: 6'

### Câu 6:

In [9]:
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name:str, yob:int):
        self._name = name
        self._yob = yob

    @abstractmethod
    def describe(self):
        pass


class Teacher(Person):
    def __init__(self, name: str, yob: int, subject:str):
        super().__init__(name, yob)
        self._subject = subject

    def describe(self):
        return  f'Name: {self._name} - Yob: {self._yob} - subject: {self._subject}'
    

teacher1 = Teacher(name='teacherZ2023', yob=1991, subject='History')
teacher1.describe()

'Name: teacherZ2023 - Yob: 1991 - subject: History'

### Câu 7.

In [11]:
class Person(ABC):
    def __init__(self, name:str, yob:int):
        self._name = name
        self._yob = yob

    @abstractmethod
    def describe(self):
        pass


class Doctor(Person):
    def __init__(self, name: str, yob: int, specialist:str):
        super().__init__(name, yob)
        self._specialist = specialist

    def describe(self):
        return  f'Name: {self._name} - Yob: {self._yob} - specialist: {self._specialist}'
    

doctor1 = Doctor(name='doctorZ2023', yob=1982, specialist='Endorinologists')
doctor1.describe()

'Name: doctorZ2023 - Yob: 1982 - specialist: Endorinologists'

### Câu 8.

In [14]:
class Ward:
    def __init__(self, name:str):
        self.__name = name
        self.__listPeople = list()

    def add_person(self, person:Person):
        self.__listPeople.append(person)

    def describe(self):
        print(f'Ward Name: {self.__name}')
        for p in self.__listPeople:
            p.describe()

    def count_doctor(self):
        count = 0
        for p in self.__listPeople:
            if type(p) == Doctor:
                count += 1
        
        return f'Number Doctor: {count}'

        
    

student1 = Student(name='studentA', yob=2010, grade='7')
teacher1 = Teacher(name='teacher1', yob=1969, subject='Math')
teacher2 = Teacher(name='teacher2', yob=1995, subject='History')
doctor1 = Doctor(name='doctor1', yob=1945, specialist='Endocrinologists')

ward1 = Ward(name='Ward1')
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)

print(ward1.count_doctor())
doctor2 = Doctor(name='doctor2', yob=1975, specialist='Cardiologists')
ward1.add_person(doctor2)
print(ward1.count_doctor())

Number Doctor: 1
Number Doctor: 2


### Câu 9:

In [15]:
class Mystack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_full(self):
        return len(self.__stack) == self.__capacity
    
    def push(self, value):
        self.__stack.append(value)


stack1 = Mystack(capacity=5)
stack1.push(1)

print(stack1.is_full())

stack1.push(2)
print(stack1.is_full())

False
False


### Câu 10

In [4]:
class MyStack:
    def __init__(self, capacity:int):
        self.__capacity = capacity
        self.__stack = []

    def is_full(self):
        return len(self.__stack) == self.__capacity
    
    def push(self, value):
        self.__stack.append(value)

    def top(self):
        return self.__stack[-1]
    

stack1 = MyStack(capacity=5)
stack1.push(1)

stack1.push(2)
print(stack1.top())

2


### Câu 11

In [3]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def is_full(self):
        return len(self.__queue) == self.__capacity
    
    def enqueue(self, value):
        self.__queue.append(value)


queue1 = MyQueue(capacity=5)
queue1.enqueue(1)

queue1.enqueue(2)
print(queue1.is_full())


False


In [29]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def isEmpty(self):
        return len(self.__queue) == 0
    
    def is_full(self):
        return len(self.__queue) == self.__capacity
    
    def dequeue(self):
        self.__queue.pop(0)

    def enqueue(self, value):
        self.__queue.append(value)

    def front(self):
        return self.__queue[0]
    
    def __repr__(self):
        my_queue = ', '.join(str(num) for num in self.__queue)
        return my_queue


    
    
    

queue1 = MyQueue(capacity=5)
queue1.enqueue(1)
queue1.enqueue(2)
print(queue1)
print(queue1.front())
queue1.dequeue()
print(queue1)

1, 2
1
2


In [1]:
class AdditionValue:
    def __init__(self, value, maxValue=0):
        self.value = value
        self.maxValue = maxValue

    def __iter__(self):
        self.n = 0
        return self
    
    def __next__(self):
        if self.n <= self.maxValue:
            result = self.n + self.value
            self.n += 1

            return result
        else:
            raise StopIteration
        


In [2]:
numbers = AdditionValue(5, 2)
for number in numbers:
    print(number)

5
6
7


In [3]:
class Node:
    def __init__(self, data = None):
        self.data = data
        self.next = None


class SinglyLinkedList:
    def __init__(self):
        self.head = None

    def __iter__(self):
        self.current = self.head
        return self
    
    def __next__(self):
        if self.current is not None:
            node = self.current

            #update
            self.current = self.current.next

            return node
        else:
            raise StopIteration
        
        

In [4]:
n1 = Node(1)
n2 = Node(2)
n3 = Node(3)
n4 = Node(4)

n1.next = n2
n2.next = n3
n3.next = n4


In [5]:
llist = SinglyLinkedList()
llist.head = n1

In [6]:
for node in llist:
    print(node.data)

1
2
3
4
